### ISSUE TITLE
Development status

### ISSUE THREAD

**Issue by edimoldovan** [mirceaalexandru/seneca-riak-store#1]
What is the status of this plugin? Is it still under development? Is it maintained?

**Comment by mirceaalexandru** [comment]
Yes, it is maintained and could be also some changes soon for this, to support new seneca implementation.

**Comment by edimoldovan** [comment]
Also, I am able to install it on node v4. Should I submit a but for that?

**Comment by mirceaalexandru** [comment]
Yes please
