### ISSUE TITLE
Unable to use seneca-riak-store with node v4

### ISSUE THREAD

**Issue by edimoldovan** [mirceaalexandru/seneca-riak-store#2]
Just tried a `npm install --save seneca-riak-store` and it failed complaining about a module called `wtf8`. Not being sure if that module is still necessary with latest node, I am submitting this here for now.

**Comment by mirceaalexandru** [comment]
Sorry for not checking this for some time. Now I am working now to update this plugin, I am using the basho-riak-client that is the official library. After changing the riak library no issue appear with node - 4.2.2 - so I think I can close this issue for now.

Please re-open if something is not right on your node version.

This version will be published soon, is now under testing.

**Comment by edimoldovan** [comment]
@mirceaalexandru Awesome, thanks. Could you please post a comment here when it has been published? I am really looking forward to using it.

**Comment by mirceaalexandru** [comment]
@edimoldovan yes, of course.

Keep in mind that because I am changing the riak library the options for connect are also changed. I will write all details in the Readme. 

You will be also able to test it - to see how it works - by using Docker, this is part of the testing procedure for all Seneca store plugins.

**Comment by edimoldovan** [comment]
@mirceaalexandru Great, looking forward to playing with it! Thanks!

**Comment by mirceaalexandru** [comment]
@edimoldovan 

I just published it, version 1.0.0

https://www.npmjs.com/package/seneca-riak-store

Thank You
